# ======= CONFIGURATION =======

# Output directory where the final executable will be produced
# and where files generated by Verilator are stored
BUILD_DIR=build

# Name of the generated executable
OUT=bench

# Top-level verilog module
TOP=max4.v

# C++ files
CPP=bench.cpp

# ======= BUILD RULES =======

# Name of .mk file generated by Verilator
VERILATOR_MK=V$(basename $(TOP)).mk

all: design $(OUT)

design: $(TOP)
	verilator -Wall -cc $(TOP) --Mdir $(BUILD_DIR) -o $(OUT) --exe $(CPP)

$(OUT): design
	$(MAKE) -C $(BUILD_DIR) -f $(VERILATOR_MK) $(OUT)

sim:
	@$(BUILD_DIR)/$(OUT)

clean:
	rm -rf $(BUILD_DIR)
